using UnityEngine;
using UnityEngine.Serialization;

namespace Map
{
    /// <summary>
    /// Represents a type of tile in the game world.
    /// </summary>
    [CreateAssetMenu(fileName = "New TileType", menuName = "ProjectCustomer/TileType")]
    public class TileType : ScriptableObject
    {
        /// <summary>
        /// Indicates whether this tile can be burned.
        /// </summary>
        public bool isBurnable;

        /// <summary>
        /// Indicates whether this tile is a water source.
        /// </summary>
        public bool isWaterSource;

        /// <summary>
        /// Indicates whether this tile can recover from being burned.
        /// </summary>
        public bool canRecover;

        /// <summary>
        /// The time it takes for this tile to burn.
        /// </summary>
        public int burnTime;

        /// <summary>
        /// The money income generated by this tile
        /// </summary>
        public int revenue;

        public int natureYield;

        /// <summary>
        /// The GameObject representing the neutral state of this tile type.
        /// </summary>
        public GameObject gfxNeutral;

        /// <summary>
        /// The GameObject representing the burning state of this tile type.
        /// </summary>
        public GameObject gfxBurning;

        /// <summary>
        /// The GameObject representing the recovering state of this tile type.
        /// </summary>
        public GameObject gfxBurned;

        public bool isNaturePointSource;
        [Range(0,100)]
        public int fireSpreadChance;

        public AudioClip placeSound;
        public AudioClip igniteSound;
        public AudioClip extinguishSound;
        public Sprite sprite;
    }
}
